"""empty message

Revision ID: 101f06ec28fb
Revises: 63b5250011d6
Create Date: 2020-06-23 18:23:01.583773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101f06ec28fb'
down_revision = '63b5250011d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('front_user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('realname', sa.String(length=30), nullable=True),
    sa.Column('avatar', sa.String(length=80), nullable=True),
    sa.Column('signature', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FAMALE', 'SECRET', 'UNKNOWN', name='genderenum'), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telephone')
    )
    op.create_foreign_key(None, 'cms_role_user', 'cms_user', ['cms_user_id'], ['id'])
    op.create_foreign_key(None, 'cms_role_user', 'cms_role', ['cms_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cms_role_user', type_='foreignkey')
    op.drop_constraint(None, 'cms_role_user', type_='foreignkey')
    op.drop_table('front_user')
    # ### end Alembic commands ###
