"""empty message

Revision ID: 23fa298b6e40
Revises: 495dbcec29c8
Create Date: 2020-06-27 18:51:35.614598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23fa298b6e40'
down_revision = '495dbcec29c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'is_delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('is_delete', mysql.ENUM('DELETE', 'NOT_DELETE'), nullable=True))
    # ### end Alembic commands ###
