"""empty message

Revision ID: 3e67b206f622
Revises: b26eb547a773
Create Date: 2020-07-01 20:23:43.508828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e67b206f622'
down_revision = 'b26eb547a773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_delete')
    # ### end Alembic commands ###
