"""empty message

Revision ID: 418954f97705
Revises: dbdc069de73b
Create Date: 2020-06-27 12:06:51.146235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418954f97705'
down_revision = 'dbdc069de73b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=False),
    sa.Column('link_url', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banner')
    # ### end Alembic commands ###
