"""empty message

Revision ID: 4738817cef26
Revises: 88b0d07a7f54
Create Date: 2020-06-27 13:50:51.943960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4738817cef26'
down_revision = '88b0d07a7f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('image_url', sa.String(length=255), nullable=False))
    op.add_column('banner', sa.Column('link_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'link_url')
    op.drop_column('banner', 'image_url')
    # ### end Alembic commands ###
