"""empty message

Revision ID: 495dbcec29c8
Revises: 6a31d802985b
Create Date: 2020-06-27 18:07:17.650877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495dbcec29c8'
down_revision = '6a31d802985b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('is_delete', sa.Enum('DELETE', 'NOT_DELETE', name='deleteenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'is_delete')
    # ### end Alembic commands ###
