"""empty message

Revision ID: 6a31d802985b
Revises: c3fa96c8ba5e
Create Date: 2020-06-27 18:07:01.812105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a31d802985b'
down_revision = 'c3fa96c8ba5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'is_delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('is_delete', mysql.ENUM('DELETE', 'NOT_DELETE'), nullable=True))
    # ### end Alembic commands ###
