"""empty message

Revision ID: 88b0d07a7f54
Revises: 418954f97705
Create Date: 2020-06-27 13:50:29.644760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88b0d07a7f54'
down_revision = '418954f97705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'link_url')
    op.drop_column('banner', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('image_url', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('banner', sa.Column('link_url', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
