"""empty message

Revision ID: b18839d4793f
Revises: 23fa298b6e40
Create Date: 2020-06-27 18:52:09.838233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18839d4793f'
down_revision = '23fa298b6e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('is_delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'is_delete')
    # ### end Alembic commands ###
