"""empty message

Revision ID: c3fa96c8ba5e
Revises: e66cdc55820a
Create Date: 2020-06-27 17:35:15.751809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fa96c8ba5e'
down_revision = 'e66cdc55820a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('is_delete', sa.Enum('DELETE', 'NOT_DELETE', name='deleteenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'is_delete')
    # ### end Alembic commands ###
