"""empty message

Revision ID: f3615f2316eb
Revises: 386e1feb9b2d
Create Date: 2020-07-04 20:06:46.111666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3615f2316eb'
down_revision = '386e1feb9b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('read_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'read_count')
    op.drop_column('post', 'like_count')
    op.drop_column('post', 'comment_count')
    # ### end Alembic commands ###
