"""empty message

Revision ID: f7a47bdbaa71
Revises: 99eda37c54a8
Create Date: 2020-05-18 20:41:53.508066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7a47bdbaa71'
down_revision = '99eda37c54a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', sa.String(length=100), nullable=False))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###
